### ISSUE TITLE
Checklist HF layer

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#956]
## Facility Management
- [ ] Create
- [ ] Update
- [ ] Close
- [ ] Pause
- [ ] Resume

## Survey Management
- [ ] Create
- [ ] Update? (Or is this a copy operation)

- [ ] Workspace Management
- [ ] Project Management

## Dashboarding
- [ ] Parse SurveyJS survey structure
- [ ] Parse data using the structure
- [ ] Expose structure to the element builder in dashboards
- [ ] Filter data based on the survey structure

**Comment by joester89** [comment]
Survey management - update: currently it is updating the survey. In my notes I found that the plan was that we do allow updating of surveys but it is the responsibility of the "updater" that it is backwards compatible. Do we stick with this or change the approach?

**Comment by joester89** [comment]
I can pick up the pause/resume/close. Lets quickly discuss how after the meeting.
